---
- name: Ensure qa user exists
  ansible.builtin.user:
    name: "{{ qa_username }}"
    state: present
    shell: "{{ qa_shell }}"
    create_home: true
    groups: sudo
    append: true
  tags:
    - user

- name: Set password for qa user
  ansible.builtin.user:
    name: "{{ qa_username }}"
    password: "{{ qa_password | password_hash('sha512') }}"
  tags:
    - password

- name: Display generated password
  ansible.builtin.debug:
    msg: "Password for qa user: {{ qa_password }}"
  tags:
    - password

- name: Create .ssh directory for qa user
  ansible.builtin.file:
    path: /home/{{ qa_username }}/.ssh
    state: directory
    owner: "{{ qa_username }}"
    group: "{{ qa_username }}"
    mode: '0700'
  tags:
    - ssh

- name: Generate SSH key pair for qa user
  ansible.builtin.user:
    name: "{{ qa_username }}"
    generate_ssh_key: true
    ssh_key_type: "{{ qa_ssh_key_type }}"
    ssh_key_file: .ssh/id_{{ qa_ssh_key_type }}
    ssh_key_comment: "qa_user_key"
  tags:
    - ssh

- name: Get generated public key
  ansible.builtin.slurp:
    src: /home/{{ qa_username }}/.ssh/id_{{ qa_ssh_key_type }}.pub
  register: qa_public_key
  tags:
    - ssh

- name: Display public SSH key
  ansible.builtin.debug:
    msg: "Public SSH key for qa user:\n{{ qa_public_key['content'] | b64decode }}"
  tags:
    - ssh
